# Generated by Django 2.2.24 on 2021-11-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Сategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Material_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_material_type', models.CharField(max_length=20, verbose_name='Тип материала')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addition.Сategories')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_material', models.CharField(max_length=20, verbose_name='Материал')),
                ('unit', models.CharField(choices=[('Метр', 'Метр'), ('Литр', 'Литр'), ('Грамм', 'Грамм'), ('Килограмм', 'Килограмм'), ('Штука', 'Штука'), ('Упоковка', 'Упоковка')], default='Метр', max_length=20, verbose_name='Единицы измерения')),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('ean', models.IntegerField(unique=True, verbose_name='Значения штрихкода')),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addition.Material_type')),
            ],
        ),
        migrations.CreateModel(
            name='Coming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True, verbose_name='Количество')),
                ('general_price', models.FloatField(null=True, verbose_name='Общая цена')),
                ('unit_price', models.FloatField(null=True, verbose_name='Цена за единицу')),
                ('currency', models.CharField(choices=[('Доллар', 'Доллар'), ('Евро', 'Евро'), ('Рубль(Россия)', 'Рубль(Росиия)'), ('Рубль(Беларусь)', 'Рубль(Беларусь)')], default='Доллар', max_length=20, verbose_name='Валюта')),
                ('date', models.DateField(verbose_name='Дата')),
                ('warehouse', models.CharField(choices=[('Скалад 54', 'Скалад 54'), ('Склад 50', 'Склад 50')], max_length=25, verbose_name='Склад')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addition.Material')),
            ],
        ),
    ]
