# Generated by Django 2.2.24 on 2021-11-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coming',
            options={'verbose_name': 'Приход', 'verbose_name_plural': 'Приходы'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='material_type',
            options={'ordering': ['title_material_type'], 'verbose_name': 'Тип материала', 'verbose_name_plural': 'Типы материалов'},
        ),
        migrations.AlterModelOptions(
            name='сategories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='coming',
            name='currency',
            field=models.CharField(choices=[('Доллар', 'Доллар'), ('Евро', 'Евро'), ('Рубль(Россия)', 'Рубль(Росcия)'), ('Рубль(Беларусь)', 'Рубль(Беларусь)')], default='Доллар', max_length=20, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='coming',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addition.Material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ean',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Значения штрихкода'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addition.Material_type', verbose_name='Тип материала'),
        ),
        migrations.AlterField(
            model_name='material_type',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addition.Сategories', verbose_name='Категория'),
        ),
    ]
