# Generated by Django 2.2.24 on 2021-11-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0002_auto_20211108_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ean',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значения штрихкода'),
        ),
    ]
