# Generated by Django 2.2.24 on 2021-11-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0003_auto_20211109_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateTimeField(verbose_name='Дата выдачи')),
                ('date_of_delivery', models.DateTimeField(verbose_name='Дата сдачи')),
                ('worker', models.CharField(max_length=25, verbose_name='Работник')),
                ('tool', models.CharField(max_length=25, verbose_name='Инструмент')),
            ],
        ),
        migrations.AlterField(
            model_name='coming',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='coming',
            name='warehouse',
            field=models.CharField(choices=[('Скалад 57', 'Склад 57'), ('Склад 50', 'Склад 50')], default='Склад 50', max_length=25, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('Метр', 'Метр'), ('Литр', 'Литр'), ('Грамм', 'Грамм'), ('Килограмм', 'Килограмм'), ('Штука', 'Штука'), ('Упоковка', 'Упоковка')], default='Метр', max_length=20, verbose_name='Ед измерения'),
        ),
    ]
