# Generated by Django 2.2.24 on 2021-11-29 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0004_auto_20211123_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Аренду', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AddField(
            model_name='rent',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addition.Material', verbose_name='материал'),
        ),
    ]
