# Generated by Django 2.2.24 on 2021-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0005_auto_20211129_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='ean',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Значения штрихкода'),
        ),
    ]
