# Generated by Django 2.2.24 on 2021-11-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0008_auto_20211130_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='coming',
        ),
    ]
