# Generated by Django 2.2.24 on 2021-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0009_remove_material_coming'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
    ]
