# Generated by Django 2.2.24 on 2021-12-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0010_rent_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coming',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addition.Material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи'),
        ),
    ]
