# Generated by Django 2.2.24 on 2021-12-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0012_auto_20211213_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date_of_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи'),
        ),
    ]
