# Generated by Django 2.2.24 on 2021-12-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0014_auto_20211214_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи'),
        ),
    ]
