# Generated by Django 2.2.24 on 2021-12-14 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0015_auto_20211214_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date_of_issue',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
        ),
    ]
