# Generated by Django 2.2.24 on 2022-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0017_auto_20211222_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='tool',
        ),
        migrations.AlterField(
            model_name='material',
            name='barcode',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Штрихкод'),
        ),
    ]
