# Generated by Django 2.2.24 on 2022-01-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0018_auto_20220110_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AlterField(
            model_name='rent',
            name='worker',
            field=models.CharField(blank=True, max_length=25, verbose_name='Работник'),
        ),
    ]
