# Generated by Django 2.2.24 on 2022-01-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0020_rent_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='в наличии'),
        ),
    ]
