# Generated by Django 2.2.24 on 2022-01-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0023_auto_20220112_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='in_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='в наличии'),
        ),
    ]
