# Generated by Django 2.2.24 on 2022-01-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0024_auto_20220117_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='в наличии'),
        ),
    ]
